# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

stages:
  - stage: terraform deploy
    displayName: terraform deploy
    jobs:
      - job: deploy
        displayName: deploy
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Azure subscription 1(5878055b-ed6d-4f89-b493-40fc80beaded)'
            backendAzureRmResourceGroupName: 'swapnilpipeline'
            backendAzureRmStorageAccountName: 'swapnilstr'
            backendAzureRmContainerName: 'tfstatefile'
            backendAzureRmKey: 'terraform.tfstate'

        - task: TerraformTask@5
          displayName: terraform plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'Azure subscription 1(5878055b-ed6d-4f89-b493-40fc80beaded)'

        - task: TerraformTask@5
          displayName: terraform apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'Azure subscription 1(5878055b-ed6d-4f89-b493-40fc80beaded)'

