trigger:
- main  # Jo bhi branch se pipeline run karni ho

pool:
  name:Default

jobs:
- job: terraformbuild
  displayName: 'Terraform Pipeline with Azure Backend'
  steps:
  - checkout: self

  # Step 1: Install Terraform
  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: '1.6.6'  # Optional, you can change it

  # Step 2: Terraform Init with AzureRM backend
  - task: TerraformTaskV1@0
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'Azure subscription 1(5878055b-ed6d-4f89-b493-40fc80beaded)'
      backendAzureRmResourceGroupName: 'swapnilpipeline'
      backendAzureRmStorageAccountName: 'swapnilstr'
      backendAzureRmContainerName: 'tfstatefile'
      backendAzureRmKey: 'terraform.tfstate'

  # Step 3: Terraform Plan
  - task: TerraformTaskV1@0
    displayName: 'Terraform Plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'Azure subscription 1(5878055b-ed6d-4f89-b493-40fc80beaded)'

  # Step 4: Terraform Apply (auto-approve)
  - task: TerraformTaskV1@0
    displayName: 'Terraform Apply'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: 'Azure subscription 1(5878055b-ed6d-4f89-b493-40fc80beaded)'
      args: '-auto-approve'

