trigger:
- main

pool:
  name: Default

variables:
  TF_VERSION: '1.6.0'   # Specify Terraform version

steps:
# Step 1: Install Terraform (optional if agent already has it)
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: '$(TF_VERSION)'

# Step 2: Checkout repo
- checkout: self

# Step 3: Azure CLI - Terraform init, plan, apply
- task: AzureCLI@2
  displayName: 'Terraform Init, Plan & Apply'
  inputs:
    azureSubscription: 'tesla-infra'  # 👈 Your service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Terraform Version:"
      terraform version

      echo "Running terraform init..."
      terraform init \
        -backend-config="resource_group_name=swapnilpipeline" \
        -backend-config="storage_account_name=swapnilstr" \
        -backend-config="container_name=tfstatefile" \
        -backend-config="key=terraform.tfstate"

      echo "Running terraform plan..."
      terraform plan -out=tfplan

      echo "Running terraform apply..."
      terraform apply -auto-approve tfplan

    workingDirectory: '$(System.DefaultWorkingDirectory)'
